XDeFi-tech/walletconnect

- example/src/components/Header.tsx
- package.json
- src/constants/enums.ts
- src/controllers/providers.ts
- src/hooks/index.ts
- src/providers/injected/index.ts
- src/wallets/index.ts
**Summary**
Fixed provider event
Add arbitrum and fantom
Add hook for custom requests
> fix: event for provider

- example/src/components/Banner.tsx
- example/src/components/Header.tsx
- package.json
- src/controllers/providers.ts
- src/hooks/index.ts
- src/providers/connectors/injected.ts
- src/wallets/index.ts
Fixed switching between accounts and loading of accounts
> fix: switch accounts

- package.json
- src/components/Provider.tsx
- src/components/Spinner.tsx
- src/controllers/providers.ts
- src/core/index.tsx
- src/wallets/index.ts
Fix: ignore wrong provider for wallet
> fix: handle invalid provider connection

- README.md
- example/package.json
- package.json
- src/wallets/index.ts
Fix: issue with loading accounts fro wallet connect
> fix: loading accounts for wallet connect

- docs/providers/walletconnect.md
- docs/providers/web3auth.md
> chore: removed trash

- example/src/App.tsx
- package.json
- src/wallets/index.ts
Add hash router for github pages
> feat: add hash router

- example/src/components/Header.tsx
- package.json
- src/components/Modal/Modal.tsx
- src/components/Wallets.tsx
> feat: v.1.2.18: className for modal

- package.json
- src/hooks/events.ts
> fix: accounts state

- package.json
- src/wallets/index.ts
> fix: provider id not being passed into validateSingleProvider

- example/src/pages/MySingleProvidersApp.tsx
- package.json
- src/components/Provider.tsx
- src/controllers/providers.ts
- src/core/index.tsx
- src/helpers/types.ts
- src/providers/injected/index.ts
- src/wallets/index.ts
Bug with prioritise function on xdefi connection
https://github.com/XDeFi-tech/xdefi-extension/issues/4918
> fix: prioritise checking

- package.json
- src/components/Provider.tsx
- src/components/WalletsModal.tsx
> chore: update wording

- README.md
- example/package.json
- example/src/pages/utils.ts
- package.json
- src/controllers/providers.ts
- src/helpers/local.ts
- src/helpers/utils.ts
- src/providers/injected/index.ts
- tsconfig.json
> fix: multiwallets connection and wrong browser provider

- package.json
- src/components/DisconnectWalletsModal.tsx
> fix: [XDEFI-1395] disconnect button cursor pointer

- package.json
- src/providers/injected/index.ts
> fix: [XDEFI-1747] evm request promise

- package.json
- src/wallets/index.ts
> fix: [XDEFI-1764] remove all listeners from provider

- package.json
- src/controllers/providers.ts
- src/wallets/index.ts
> fix: [XDEFI-1763] set empty provider accounts

- package.json
- src/providers/injected/index.ts
> fix: keplr window if connected xdefi XDEFI-5937

- package.json
> [Chore] bump version to 2.1.3

- package.json
- src/controllers/providers.ts
- src/wallets/index.ts
- add typeguard for Promise.race mixed return type
- update package version to 2.1.4
> [hotfix] Fix TS issue update package version to 2.1.4

- package.json
- src/controllers/providers.ts
- src/wallets/index.ts
Revert timeouts as they does not work
> revert timeouts

- README.md
- docs/providers/walletconnect.md
> feat: update readme XDEFI-6357

- src/components/WalletsModal/SelectChainSection/SelectChainSection.constants.tsx
- src/providers/injected/index.ts
Remove: 
- Aurora 
- Juno 
- Crescent 
- Binance (not bsc) 
- Near 
- Terra
> fix: remove no longer supported chains

- .github/workflows/release-package.yml
update node version to v18 in build scripts
> fix: update node version in workflows
